const ORDER_STATUS = {
  PENDING: 'Pending',
  PREPARING: 'Preparing',
  READY_FOR_PICKUP: 'Ready for Pickup',
  SERVED: 'Served',
  OUT_FOR_DELIVERY: 'Out for Delivery',
  DELIVERED: 'Delivered',
  COMPLETED: 'Completed',
  CANCELLED: 'Cancelled',
};

const ORDER_STATUSES = Object.values(ORDER_STATUS);

const ALLOWED_TRANSITIONS = {
  [ORDER_STATUS.PENDING]: [ORDER_STATUS.PREPARING, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.PREPARING]: [ORDER_STATUS.READY_FOR_PICKUP, ORDER_STATUS.SERVED, ORDER_STATUS.OUT_FOR_DELIVERY, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.READY_FOR_PICKUP]: [ORDER_STATUS.COMPLETED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.SERVED]: [ORDER_STATUS.COMPLETED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.OUT_FOR_DELIVERY]: [ORDER_STATUS.DELIVERED],
  [ORDER_STATUS.DELIVERED]: [ORDER_STATUS.COMPLETED],
  [ORDER_STATUS.COMPLETED]: [],
  [ORDER_STATUS.CANCELLED]: [],
};

const PAYMENT_STATUS = {
  PENDING_VERIFICATION: 'Pending Verification',
  PAID: 'Paid',
  REJECTED: 'Rejected',
};

const PAYMENT_STATUSES = Object.values(PAYMENT_STATUS);

const ORDER_TYPE = {
  PICKUP: 'Pickup',
  DINE_IN: 'Dine-in',
  DELIVERY: 'Delivery',
};

const ORDER_TYPES = Object.values(ORDER_TYPE);

const PAYMENT_METHOD = {
  CASH: 'Cash',
  GCASH: 'GCash',
  MAYA: 'Maya',
  CARD: 'Card',
  CASH_ON_DELIVERY: 'Cash on Delivery',
};

const DIGITAL_PAYMENT_METHODS = [PAYMENT_METHOD.GCASH, PAYMENT_METHOD.MAYA, PAYMENT_METHOD.CARD];
const COD_METHODS = [PAYMENT_METHOD.CASH_ON_DELIVERY, PAYMENT_METHOD.CASH];

const ROLE = {
  ADMIN: 'admin',
  STAFF: 'staff',
};

const ROLES = Object.values(ROLE);

module.exports = {
  ORDER_STATUS,
  ORDER_STATUSES,
  ALLOWED_TRANSITIONS,
  PAYMENT_STATUS,
  PAYMENT_STATUSES,
  ORDER_TYPE,
  ORDER_TYPES,
  PAYMENT_METHOD,
  DIGITAL_PAYMENT_METHODS,
  COD_METHODS,
  ROLE,
  ROLES,
};
